# The URL the site will be built for
base_url = "https://filipmilo.dev"

theme = "terminimal"

title = "Filip Milosevic"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# The theme supports feeds (RSS and ATOM)
generate_feeds = true

# Use `rss.xml` for RSS feeds and `atom.xml` for ATOM.
feed_filenames = ["rss.xml", "atom.xml"]

taxonomies = [
    {name = "tags"}
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]

author = "Filip Milosevic"

logo_text = "filipmilo"

favicon = "favicon.ico"

favicon_mimetype = "image/x-icon"

accent_color = "green"

background_color = "green"

menu_items = [
    {name = "/about me", url = "$BASE_URL/about"},
    {name = "/blog", url = "$BASE_URL"},
    {name = "/cv", url = "$BASE_URL/cv.pdf"},
]
