baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Filip Milosevic'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 10

[[menus.main]]
name = 'Blog'
pageRef = '/blog'
weight = 20

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
